name: Upload to TestPyPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Setup project
      - name: "Setup project"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python3 setup.py install

      # Upload to TestPyPI
      - name: Build and Upload to TestPyPI
        run: |
          python3 setup.py sdist bdist_wheel
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
          TWINE_REPOSITORY: testpypi
